#!/bin/bash
#
# Kasutaja lisamise skript
#
#
if [ $# -ne 2 ]; then
	echo "Kasutusjuhend: $0 kasutajate_fail paroolide_fail"
else
	kasutajad=$1
	paroolid=$2
	if [ -f $kasutajad -a -r $kasutajad ] && [ -f $paroolid -a -r $paroolid ]; then
	echo "Failid korras"
#
	paste -d":" $kasutajad $paroolid >> lkyl4.txt
	for rida in $(cat lkyl4.txt)
	do
	user=$(echo "$rida" | cut -f1 -d:)
	useradd $user -m -s /bin/bash 
	echo "$rida" | chpasswd
	cat /etc/passwrd | grep $user
	cat /etc/shadow | grep $user
	done
	echo "Kasutajad loodud"
	rm lkyl4.txt
	fi
fi
